
spring:

  # 链路追踪
  zipkin:
    base-url: http://${ZIPKIN_SERVICE_HOST:127.0.0.1}:${ZIPKIN_SERVICE_PORT:9411}
  sleuth:
    sampler:
      #服务跟踪消息收集率，1代表每一条都收集，0.1代表收集百分之10
      probability: 1.0

  # DataSource StoreConfig
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_SERVICE_HOST:127.0.0.1}:${MYSQL_SERVICE_PORT:3306}/pgs_store?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:bys2018}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: LcHikariCP
      # 池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 等待来自池的连接的最大毫秒数,小于30秒重置为30秒
      connection-timeout: 30000

  # Redis Config
  redis:
    host: ${REDIS_SERVICE_HOST:127.0.0.1}
    port: ${REDIS_SERVICE_PORT_REDIS:6379}
    password: ${REDIS_PSWD:beyondsoft}
    #默认使用db2
    database: ${REDIS_DB_NO:0}
    jedis:
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 1

# eureka configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USER:fnb}:${EUREKA_PWD:fnb2019}@${EUREKA_SERVICE_HOST:192.168.7.229}:${EUREKA_SERVICE_PORT:8761}/eureka/
    registry-fetch-interval-seconds: 10
    initial-instance-info-replication-interval-seconds: 10
    instance-info-replication-interval-seconds: 10
  instance:
    # Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 10
    # Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己） 必须大于 lease-renewal-interval-in-seconds
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true

    hostname: ${spring.cloud.client.ip-address}
    instance-id: redis服务(${spring.cloud.client.ip-address}:${server.port})

# 分布式事务配置
tx-lcn:
  # 负载均衡
  ribbon:
    loadbalancer:
      dtx:
        enabled: true
  client:
    manager-address: ${SERVER_LCN_TM_SERVICE_HOST:192.168.7.229}:${SERVER_LCN_TM_SERVICE_PORT_SERVER_TM_SOCKET:8070}
    chain-level: 5

